In [2]:
import pandas as pd
import numpy as np

### Day 1
Essentials of NumPy, Pandas,
and Matplotlib

### Day 2
Creating and Manipulating Arrays

In [5]:
#Write code to import NumPy into your script. Check the version of NumPy installed.
print("The version of numpy is" , np.__version__)

The version of numpy is 2.0.2


In [8]:
#Here is a list below:
list1 = [2, 3, 4, 6]
#Create a one-dimensional array from the list above. Write another line of code to check the shape and size of your array.
list1 = np.array(list1)
list1.shape


(4,)

In [10]:
#Write a function that takes this array and returns a new array with all the values in the original array reversed.
def reversed_array(list1):
    new_array  = np.flip(list1)
    print(new_array)

reversed_array(list1)

[6 4 3 2]


In [13]:
#Create an array from the two lists above. Then write code to check the shape, dimensions, and data type of the array.
list1 = [2, 3, 4, 6]
list2 = [8, 10, 12, 14]

new_array = np.array([list1,list2])

print("Shape of the array:", new_array.shape)
print("Number of dimensions:", new_array.ndim)
print("Data type of the array:", new_array.dtype)

Shape of the array: (2, 4)
Number of dimensions: 2
Data type of the array: int64


In [15]:
#Create an array from the three (3) lists above. Take note that some of the lists contain floats. Create an array that will have an int64 data type.

list1 = [2, 3, 4, 6]
list2 = [8, 10.1, 12, 14]
list3 = [16, 18, 20, 22.1]


new_array = np.array([list1, list2, list3], dtype=np.int64)

print("Array with int64 data type:\n", new_array)
print("Data type of the array:", new_array.dtype)

Array with int64 data type:
 [[ 2  3  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
Data type of the array: int64


Is it possible to create an array of both floats and integers?

No, numpy just can take one data type per array